[versions]
xtc = "0.4.4-SNAPSHOT"
node = "7.1.0"
nodejs = "22.11.0"
npm = "10.9.0"

[plugins]
xtc = { id = "org.xtclang.xtc-plugin", version.ref = "xtc" }
node = { id = "com.github.node-gradle.node", version.ref = "node" }

[libraries]
xdk = { module = "org.xtclang:xdk", version.ref = "xtc" }
xtc-plugin = { module = "org.xtclang:xtc-plugin", version.ref = "xtc" }
node-plugin = { module = "com.github.node-gradle:gradle-node-plugin", version.ref = "node" }
